<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Correlation &amp; Regression</title>

<script src="site_libs/header-attrs-2.19/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<!--All these are favicons-->
<link rel="apple-touch-icon" sizes="180x180" href="img/logo/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/logo/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="img/logo/favicon-16x16.png">
<link rel="manifest" href="img/logo/site.webmanifest">
<link rel="mask-icon" href="img/logo/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="img/logo/favicon.ico">
<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="msapplication-config" content="img/logo/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

<!--Github Corner-->
<a href="https://github.com/SchmidtPaul/DSFAIR" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#003f75ff; color:#fff; position: absolute; top: 50; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

<!--SAS syntax highlighting-->
<!--
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.31.0/codemirror.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.31.0/codemirror.min.js"></script>
<style>
  .CodeMirror {
    border: 1px solid #eee;
    height: auto;
  }
</style>
-->

<!--Metatags = preview image when linking to social media-->

<!-- Primary Meta Tags -->
<!-- <title>Mixed Models for Agriculture in R</title> -->
<!-- <meta name="title" content="Mixed Models for Agriculture in R">  -->
<!--
<meta name="description" content="Our aim is to provide a cookbook with mixed model analyses of typical examples in life sciences (focus on agriculture/biology) and compare the possibilities or rather limitations of the R-packages nlme, lme4, glmmTMB and sommer to each other, but also to SAS’ PROC MIXED.">
-->

<!-- Open Graph / Facebook -->
<!--
<meta property="og:type" content="website">
<meta property="og:url" content="https://schmidtpaul.github.io/MMFAIR/index.html">
<meta property="og:title" content="Mixed Models for Agriculture in R">
<meta property="og:description" content="Our aim is to provide a cookbook with mixed model analyses of typical examples in life sciences (focus on agriculture/biology) and compare the possibilities or rather limitations of the R-packages nlme, lme4, glmmTMB and sommer to each other, but also to SAS’ PROC MIXED.">
<meta property="og:image" content="img/logo/ScreenshotIndex.PNG">
-->

<!-- Twitter -->
<!--
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://schmidtpaul.github.io/MMFAIR/index.html">
<meta property="twitter:title" content="Mixed Models for Agriculture in R">
<meta property="twitter:description" content="Our aim is to provide a cookbook with mixed model analyses of typical examples in life sciences (focus on agriculture/biology) and compare the possibilities or rather limitations of the R-packages nlme, lme4, glmmTMB and sommer to each other, but also to SAS’ PROC MIXED.">
<meta property="twitter:image" content="img/logo/ScreenshotIndex.PNG">
-->





<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>
<!-- DEPRECATION-BANNER-START -->
<style>
/* ===== DEPRECATION BANNER ===== */
.deprecation-banner {
    background: linear-gradient(135deg, #c62828, #e53935);
    color: white;
    padding: 24px 24px 18px;
    font-size: 15px;
    line-height: 1.6;
    text-align: center;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    position: relative;
    z-index: 9999;
}
.deprecation-banner strong {
    font-size: 17px;
}
.deprecation-banner .lang-block {
    display: inline-block;
    text-align: center;
    max-width: 600px;
    vertical-align: top;
}
.deprecation-banner .banner-divider {
    display: inline-block;
    width: 1px;
    height: 80px;
    background: rgba(255,255,255,0.4);
    margin: 0 30px;
    vertical-align: middle;
}
.deprecation-banner a.banner-link {
    color: white;
    background: rgba(255,255,255,0.2);
    padding: 6px 16px;
    border-radius: 4px;
    text-decoration: none;
    font-weight: bold;
    border: 1px solid rgba(255,255,255,0.5);
    display: inline-block;
    margin-top: 6px;
    transition: background 0.2s;
}
.deprecation-banner a.banner-link:hover {
    background: rgba(255,255,255,0.35);
}
.deprecation-banner .banner-signature {
    display: block;
    margin-top: 10px;
    font-style: italic;
    font-weight: bold;
    font-size: 17px;
    opacity: 0.9;
}
@media (max-width: 800px) {
    .deprecation-banner .lang-block {
        display: block;
        max-width: 100%;
        margin-bottom: 12px;
    }
    .deprecation-banner .banner-divider {
        display: block;
        width: 60%;
        height: 1px;
        margin: 12px auto;
    }
}
</style>
<div class="deprecation-banner">
    <div class="lang-block">
        <strong>&#9888; Hey, nice that you're here! BUT...</strong><br>
        This site is no longer maintained and may contain outdated information.
        I'm keeping it online because I once promised to never take it down &ndash;
        but I've since built a much better, up-to-date resource. I'd really
        appreciate if you checked it out and found the corresponding chapter there:<br>
        <a class="banner-link" href="https://biomathcontent.netlify.app/">&#10132; biomathcontent.netlify.app</a>
    </div>
    <span class="banner-divider"></span>
    <div class="lang-block">
        <strong>&#9888; Hi, sch&ouml;n, dass du hier bist, ABER...</strong><br>
        Diese Seite wird nicht mehr gepflegt und enth&auml;lt m&ouml;glicherweise
        veraltete Informationen. Ich habe versprochen sie online zu lassen,
        also bleibt sie stehen &ndash; aber alle Inhalte wurden &uuml;berarbeitet,
        verbessert und auf einer neuen Seite zusammengef&uuml;hrt.
        Schau bitte stattdessen dort vorbei:<br>
        <a class="banner-link" href="https://biomathcontent.netlify.app/">&#10132; biomathcontent.netlify.app</a>
    </div>
    <span class="banner-signature">- Cheers, <a href="https://schmidtpaul.github.io/" style="color:white;text-decoration:underline;">Paul</a></span>
</div>
<!-- DEPRECATION-BANNER-END -->



<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">DSFAIR</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Getting Started</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="rbasics.html">R Basics</a>
        </li>
        <li>
          <a href="cor_reg_drinks.html">Correlation &amp; Regression</a>
        </li>
        <li>
          <a href="baddata_outliers_vision.html">Bad Data &amp; Outliers</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Simple Experiments</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="CRD_Mead1993.html">crd_Mead1993</a>
        </li>
        <li>
          <a href="RCBD_ClewerScarisbrick2001.html">rcbd_ClewerScarisbrick2001</a>
        </li>
        <li>
          <a href="latsquare_Bridges1989.html">latsquare_Bridges1989</a>
        </li>
        <li>
          <a href="RCBD_2f_rice.html">rcbd_RCBD_2f_rice</a>
        </li>
        <li>
          <a href="augmented_Pattersen1994.html">augmented_Pattersen1994</a>
        </li>
        <li>
          <a href="alpha_JohnWilliams1995.html">alpha_JohnWilliams1995</a>
        </li>
        <li>
          <a href="rowcol_KemptonFox1997.html">rowcol_KemptonFox1997</a>
        </li>
        <li>
          <a href="splitplot_GomezGomez1984.html">splitplot_GomezGomez1984</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Complex Experiments</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="subsampling_Piepho1997.html">subsampling_Piepho1997</a>
        </li>
        <li>
          <a href="splitplot_StreetFruit.html">splitplot_StreetFruit</a>
        </li>
        <li>
          <a href="Repeated_RCBD_PiephoEdmondson2018.html">rcbd_PiephoEdmondson2018</a>
        </li>
      </ul>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Summaries
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="compactletterdisplay.html">Compact Letter Display</a>
    </li>
    <li>
      <a href="DesigningExperiments.html">Designing experiments</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://schmidtpaul.github.io/">Contact</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Correlation &amp; Regression</h1>

</div>


<p>This chapter is trying to give you a feeling for what correlation and
(simple linear) regression is. I am aware that the example data doesn’t
have anything to do with agriculture or related fields, but I decided to
keep it because it allows for an intuitive conclusion at the end.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  modelbased, <span class="co"># get model predictions/expectations</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  tidyverse <span class="co"># data import and handling</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>This is data I made up: Peter and Max went out multiple evenings and
at the end of every evening wrote down how many drinks they had and what
the alcohol content in their blood was.</p>
<div id="import" class="section level2">
<h2>Import</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data (import via URL)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dataURL <span class="ot">&lt;-</span> <span class="st">&quot;https://raw.githubusercontent.com/SchmidtPaul/DSFAIR/master/data/DrinksPeterMax.csv&quot;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(dataURL)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat</span></code></pre></div>
<pre><code>## # A tibble: 20 × 3
##    Person drinks blood_alc
##    &lt;chr&gt;   &lt;dbl&gt;     &lt;dbl&gt;
##  1 Max         1       0.2
##  2 Max         2       0.3
##  3 Max         3       0.5
##  4 Max         3       0.6
##  5 Max         4       0.6
##  6 Max         4       0.5
##  7 Max         4       0.7
##  8 Max         5       0.6
##  9 Max         7       0.8
## 10 Max         8       1  
## 11 Peter       1       0.1
## 12 Peter       1       0.1
## 13 Peter       1       0.2
## 14 Peter       1       0.2
## 15 Peter       1       0.1
## 16 Peter       3       0.3
## 17 Peter       5       0.5
## 18 Peter       6       0.8
## 19 Peter       8       0.9
## 20 Peter       9       1.3</code></pre>
</div>
<div id="goal" class="section level2">
<h2>Goal</h2>
<p>The goal of this analysis is to answer the question how the number of
drinks relates to the blood alcohol level. Note that we will completely
ignore the column <code>Person</code>, since we do not care whether data
came from Peter or Max in this chapter. Thus, we only focus on the two
<em>numeric</em> columns <code>drinks</code> and
<code>blood_alc</code>.</p>
</div>
<div id="exploring" class="section level2">
<h2>Exploring</h2>
<p>To quickly get a first feeling for this dataset, we can use
<code>summary()</code> and draw a <code>plot()</code>:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat)</span></code></pre></div>
<pre><code>##     Person              drinks       blood_alc    
##  Length:20          Min.   :1.00   Min.   :0.100  
##  Class :character   1st Qu.:1.00   1st Qu.:0.200  
##  Mode  :character   Median :3.50   Median :0.500  
##                     Mean   :3.85   Mean   :0.515  
##                     3rd Qu.:5.25   3rd Qu.:0.725  
##                     Max.   :9.00   Max.   :1.300</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">y =</span> dat<span class="sc">$</span>blood_alc, <span class="at">x =</span> dat<span class="sc">$</span>drinks)</span></code></pre></div>
<p><img src="cor_reg_drinks_files/figure-html/unnamed-chunk-3-1.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Apparently, the number of drinks ranges from 1 to 9 with a mean of
3.85, while the measured blood alcohol levels range from 0.1 to 1.3 with
a mean of 0.515. The plot shows a clear trend of increasing blood
alcohol levels with a higher number of drinks - which is what we would
expect.</p>
<p>Here is the same plot created with {ggplot2}:</p>
<div class="sourceCode" id="cb7"><pre
class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> drinks, <span class="at">y =</span> blood_alc)) <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Number of drinks&quot;</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">9</span>),</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">9</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Blood alcohol content&quot;</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.1</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="cor_reg_drinks_files/figure-html/unnamed-chunk-4-1.png" width="60%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="correlation" class="section level1">
<h1>Correlation</h1>
<div id="what-is-it" class="section level2">
<h2>What is it?</h2>
<p>One way of actually putting a number on this relationship is to
estimate the correlation. When people talk about correlation (<span
class="math inline">\(\rho\)</span> or <span
class="math inline">\(r\)</span>) in statistics, they usually refer to
the <a
href="https://www.wikiwand.com/en/Pearson_correlation_coefficient">Pearson
correlation coefficient</a>, which is a measure of linear correlation
between two numeric variables. Correlation can only have values between
-1 and 1, where 0 means <em>no correlation</em>, while all other
possible values are either negative or positive correlations. The
farther away from 0, the stronger is the correlation.</p>
<!-- # ```{r pressure, echo=FALSE, out.width = '60%', fig.align='center'} -->
<!-- # knitr::include_graphics("img/correlation.png", error = FALSE) -->
<!-- # ``` -->
<center>
<img src="images/img/correlation.png" style="width:50%">
</center>
<p>Simply put, a positive correlation means <em>“if one variable gets
bigger, the other also gets bigger”</em> and a negative correlation
means <em>“if one variable gets bigger, the other gets smaller”</em>.
Therefore, it does not matter which of the two variables is the first
(“x”) or the second (“y”) variable. Thus, a correlation estimate is not
like a model and it cannot make predictions. Finally, <a
href="https://www.wikiwand.com/en/Correlation_does_not_imply_causation"><em>“correlation
does not imply causation”</em></a> means that just because you found a
(strong) correlation between two things, you cannot conclude that there
is a cause-and-effect relationship between the two, which becomes clear
when looking at <a
href="https://www.tylervigen.com/spurious-correlations">these
examples</a>.</p>
</div>
<div id="how-to-get-it" class="section level2">
<h2>How to get it</h2>
<p>If you only want to get the actual correlation estimate, you can use
the function <code>cor()</code> and provide the two numeric variables
(as vectors):</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dat<span class="sc">$</span>drinks, dat<span class="sc">$</span>blood_alc)</span></code></pre></div>
<pre><code>## [1] 0.9559151</code></pre>
<p>So the correlation between number of drinks and blood alcohol content
in our sample is ca. 0.96 and thus very strong, since it is almost
1.</p>
</div>
<div id="how-to-test-it" class="section level2">
<h2>How to test it</h2>
<p>If you would like additional information, such as a confidence
interval and a test resulting in a p-value, you can use
<code>cor.test()</code> instead of <code>cor()</code>:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(dat<span class="sc">$</span>drinks, dat<span class="sc">$</span>blood_alc)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  dat$drinks and dat$blood_alc
## t = 13.811, df = 18, p-value = 5.089e-11
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.8897837 0.9827293
## sample estimates:
##       cor 
## 0.9559151</code></pre>
<p>Looking at this longer output, you can see the sample estimate at the
bottom, a confidence interval above it and a p-value with the
corresponding test hypothesis above that. Run <code>?cor.test()</code>
and look at the “Details” section for more info. Here, our correlation
estimate of 0.96 is signficantly different from 0, since the p-value is
0.0000000000509 and therefore <span class="math inline">\(&lt;
0.05\)</span>. Furthermore, the confidence interval is 0.890 - 0.983
meaning that we are 95% sure that the true correlation is somewhere in
that range.</p>
<aside>
You can get the results in a tidy format by using the
<code>tidy()</code> function from <a
href="https://broom.tidymodels.org/">{broom}</a>.
</aside>
<blockquote>
<p>Note that correlation is a widely used statistic so that there are
several R packages that deal with it. I suggest taking a look at <a
href="https://easystats.github.io/correlation/">{correlation}</a> and <a
href="https://corrr.tidymodels.org/">{corrr}</a>.</p>
</blockquote>
</div>
</div>
<div id="simple-linear-regression" class="section level1">
<h1>Simple linear regression</h1>
<div id="what-is-it-1" class="section level2">
<h2>What is it?</h2>
<p>When people talk about regression in statistics, they usually refer
to <a href="https://www.wikiwand.com/en/Simple_linear_regression">simple
linear regression</a>, which - simply put - finds the best straight line
that goes through dots in a scatter plot of two numeric variables:</p>
<!-- # ```{r, echo=FALSE, out.width = '60%', fig.align='center'} -->
<!-- # knitr::include_graphics("img/regressionexamples.png", error = FALSE) -->
<!-- # ``` -->
<center>
<img src="img/regressionexamples.png" style="width:50%">
</center>
<p>The linear model behind such a straight line is simply:</p>
<p><span class="math display">\[ y = \alpha + \beta x\]</span></p>
<p>where <span class="math inline">\(\alpha\)</span> or <span
class="math inline">\(a\)</span> is the intercept and <span
class="math inline">\(\beta\)</span> or <span
class="math inline">\(b\)</span> is the slope, while <span
class="math inline">\(y\)</span> and <span
class="math inline">\(x\)</span> are our data points. Fitting such a
regression is really just finding the optimal estimates for <span
class="math inline">\(\alpha\)</span> and <span
class="math inline">\(\beta\)</span>.</p>
<!-- # ```{r, echo=FALSE, out.width = '60%', fig.align='center'} -->
<!-- # knitr::include_graphics("img/regressiontheory.png", error = FALSE) -->
<!-- # ``` -->
<center>
<img src="img/regressiontheory.png" style="width:50%">
</center>
<p>In contrast to correlation, a simple linear regression is a model and
it therefore matters which variable is <span
class="math inline">\(y\)</span> (dependent variable) and which is <span
class="math inline">\(x\)</span> (independent), because after fitting
the regression, the latter can be used to predict the former.</p>
</div>
<div id="how-to-get-it-1" class="section level2">
<h2>How to get it</h2>
<p>In R, we can use the <code>lm()</code> function for fitting linear
models so that it fits the simple linear regression equation shown above
easily:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> blood_alc <span class="sc">~</span> drinks, <span class="at">data =</span> dat)</span></code></pre></div>
<p>As you can see, we refer to our data object <code>dat</code> in the
<code>data =</code> argument so that in the <code>formula =</code>
argument we only need to write the names of the respective columns in
<code>dat</code>. Furthermore, we store the results in the
<code>reg</code> object. When looking at this object, we get the
following results:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>reg</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = blood_alc ~ drinks, data = dat)
## 
## Coefficients:
## (Intercept)       drinks  
##     0.04896      0.12105</code></pre>
<p>First, our command is repeated and then the “Coefficients” are shown,
which are indeed the estimates for <span
class="math inline">\(a\)</span> and <span
class="math inline">\(b\)</span>. So the best straight line is:</p>
<p><span class="math display">\[ bloodalc = 0.049 + 0.121 * drinks
\]</span> which looks like this:</p>
<div class="sourceCode" id="cb15"><pre
class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> drinks, <span class="at">y =</span> blood_alc)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> <span class="st">&quot;y ~ x&quot;</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fullrange =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#769bbb&quot;</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Number of drinks&quot;</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">9</span>),</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">9</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Blood alcohol content&quot;</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>),</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.1</span>))</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="cor_reg_drinks_files/figure-html/unnamed-chunk-10-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p>Here is a little more info why
<code>formula = blood_alc ~ drinks</code> leads to R estimating the
<span class="math inline">\(a\)</span> and <span
class="math inline">\(b\)</span> we want. What makes sense is that
<code>blood_alc</code> is <span class="math inline">\(y\)</span>,
<code>drinks</code> is <span class="math inline">\(x\)</span> and
<code>~</code> would therefore be the <span
class="math inline">\(=\)</span> in our equation. However, how come we
never had to write anything about <span class="math inline">\(a\)</span>
or <span class="math inline">\(b\)</span>? The answer is that (i) when
fitting a linear model, there is usually always an intercept (=<span
class="math inline">\(a\)</span>) by default and (ii) when writing a
numeric variable (=<code>drinks</code>) as on the right side of the
equation, it will automatically be assumed to have a slope (=<span
class="math inline">\(b\)</span>) multiplied with it. Accordingly,
<code>blood_alc ~ drinks</code> automatically translates to
<code>blood_alc = a + b*drinks</code> so to speak.</p>
</div>
<div id="is-this-right" class="section level2">
<h2>Is this right?</h2>
<p>After fitting a model, you may use it to make predictions. Here is
one way of obtaining the expected blood alcohol content for having 0, 1,
2, or 3 drinks is according to our simple linear regression:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>preddat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">drinks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">3</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_expectation</span>(<span class="at">model =</span> reg, <span class="at">data =</span> preddat)</span></code></pre></div>
<pre><code>## Model-based Expectation
## 
## drinks | Predicted |   SE |        95% CI
## -----------------------------------------
## 0.00   |      0.05 | 0.04 | [-0.04, 0.13]
## 1.00   |      0.17 | 0.03 | [ 0.10, 0.24]
## 2.00   |      0.29 | 0.03 | [ 0.23, 0.35]
## 3.00   |      0.41 | 0.02 | [ 0.36, 0.46]
## 
## Variable predicted: blood_alc</code></pre>
<aside>
You may use <code>predict(reg, preddat)</code> instead of
<code>estimate_expectation()</code> if you don’t want to rely on <a
href="https://easystats.github.io/modelbased/">{modelbased}</a> as an
extra package.
</aside>
<p>You may notice that according to our model, the expected alcohol
content in your blood when having 0 drinks is actually ca. 0.05 and thus
larger than 0. This is obviously not true in real life. Instead, the
true intercept should actually be exactly 0, so what went wrong?</p>
<p>First of all, data will never be perfect in the sense that the when a
parameter really is e.g. 42, its estimate based on measured data is also
exactly 42.000000… . Instead, there are e.g. measurement errors: Peter
and Max may have forgotten a drink or two or their device to measure the
alcohol content is not precise enough. In fact, this would most likely
be the underlying reason here - but remember that I made the data
up.</p>
<p>So I would like you to think about the issue from two other
angles:</p>
<ol style="list-style-type: decimal">
<li>Are the results really saying the intercept is &gt; 0?</li>
<li>Did we even ask the right question or should we have fitted a
different model?</li>
</ol>
<div id="are-the-results-really-saying-the-intercept-is-0"
class="section level3">
<h3>Are the results really saying the intercept is &gt; 0?</h3>
<p>No, they are not. Yes, the sample estimate for the intercept is
0.04896, but when looking at more detailed information via
e.g. <code>summary()</code>,</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = blood_alc ~ drinks, data = dat)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.154206 -0.070011 -0.004206  0.039202  0.187891 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.048963   0.040592   1.206    0.243    
## drinks      0.121049   0.008764  13.811 5.09e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1009 on 18 degrees of freedom
## Multiple R-squared:  0.9138, Adjusted R-squared:  0.909 
## F-statistic: 190.8 on 1 and 18 DF,  p-value: 5.089e-11</code></pre>
<p>you can see that the p-value for the intercept is 0.243, which is
larger than 0.05 and thus not significantly different from 0. A second
indication can be found when looking at the confidence interval of the
expected value for having 0 drinks in the table above:
<code>[-0.04, 0.13]</code>. This interval actually includes 0 which
suggests that the true expected blood alcohol content for having 0
drinks may indeed be 0.</p>
<aside>
You can get the results in a tidy format by using the
<code>tidy()</code> and <code>glance()</code> functions from <a
href="https://broom.tidymodels.org/">{broom}</a>.
</aside>
</div>
<div id="should-we-have-fitted-a-different-model"
class="section level3">
<h3>Should we have fitted a different model?</h3>
<p>We certainly <strong>could</strong> have and we will actually do it
now. It must be clear that statistically speaking there was nothing
wrong with our analysis. However, from a biological standpoint or in
other words - because of our background knowledge and expertise as
scientists, we could have indeed actively decided for a regression
analysis that does <strong>not</strong> have an intercept and is thus
forced to start 0 in terms of blood alcohol content. After all,
statistics is just a tool to help us make conclusions. It is a powerful
tool, but it will always be our responsibility to “ask the right
questions” i.e. apply expedient methods.</p>
<p>A simple linear regression without an intercept is strictly speaking
no longer “simple”, since it no longer has the typical equation:</p>
<p><span class="math display">\[ y = \beta x\]</span> To let
<code>lm()</code> that it should not estimate the default intercept, we
simply add <code>0 +</code> right after the <code>~</code>. As expected,
we only get one estimate for the slope:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>reg_noint <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> blood_alc <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> drinks, <span class="at">data =</span> dat)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>reg_noint</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = blood_alc ~ 0 + drinks, data = dat)
## 
## Coefficients:
## drinks  
## 0.1298</code></pre>
<p>meaning that this regression with no intercept is estimated as</p>
<p><span class="math display">\[ bloodalc = 0.1298 * drinks
\]</span></p>
<p>and must definitely predict 0 <code>blood_alc</code> when having 0
<code>drinks</code>. As a final result, we can compare both regression
lines visually in a ggplot:</p>
<div class="sourceCode" id="cb22"><pre
class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">x =</span> drinks, <span class="at">y =</span> blood_alc)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> <span class="st">&quot;y ~ x&quot;</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">fullrange =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#769bbb&quot;</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">formula =</span> <span class="st">&quot;y ~ 0 + x&quot;</span>,</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">se =</span> <span class="cn">FALSE</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">fullrange =</span> <span class="cn">TRUE</span>,</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;#DF9A57&quot;</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Number of drinks&quot;</span>,</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">9</span>),</span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">9</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Blood alcohol content&quot;</span>,</span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="cn">NA</span>),</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.1</span>))</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<p><img src="cor_reg_drinks_files/figure-html/unnamed-chunk-14-1.png" width="60%" style="display: block; margin: auto;" /></p>
<p><strong>R-Code and exercise solutions</strong></p>
<p>Please <a
href="https://github.com/SchmidtPaul/DSFAIR/tree/master/Rpurl"
target="_blank">click here</a> to find a folder with <code>.R</code>
files. Each file contains</p>
<ul>
<li>the entire R-code of each example combined, including</li>
<li>solutions to the respective exercise(s).</li>
</ul>
</div>
</div>
</div>

&nbsp;
<hr />
<p style="text-align: center;">Please feel free to contact me about any of this!</p>
<p style="text-align: center;"><span style="color: #003f75ff;"><em>schmidtpaul1989@outlook.com</em></span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://www.researchgate.net/profile/Paul_Schmidt17" class="fa fa-pencil" style="color: #003f75ff;"></a>
    <a href="https://www.linkedin.com/in/schmidtpaul1989/" class="fa fa-linkedin" style="color: #003f75ff;"></a>
    <a href="https://www.xing.com/profile/Paul_Schmidt393/cv" class="fa fa-xing" style="color: #003f75ff;"></a>
    <a href="https://github.com/SchmidtPaul/" class="fa fa-github" style="color: #003f75ff;"></a>
</p>

<a href="https://hits.seeyoufarm.com"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fschmidtpaul.github.io%2FDSFAIR%2F&count_bg=%23003F75&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false" class="center"/></a>

&nbsp;


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
