<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Repeated Measures RCBD</title>

<script src="site_libs/header-attrs-2.19/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<!--All these are favicons-->
<link rel="apple-touch-icon" sizes="180x180" href="img/logo/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/logo/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="img/logo/favicon-16x16.png">
<link rel="manifest" href="img/logo/site.webmanifest">
<link rel="mask-icon" href="img/logo/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="img/logo/favicon.ico">
<meta name="msapplication-TileColor" content="#2d89ef">
<meta name="msapplication-config" content="img/logo/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

<!--Github Corner-->
<a href="https://github.com/SchmidtPaul/DSFAIR" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#003f75ff; color:#fff; position: absolute; top: 50; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>

<!--SAS syntax highlighting-->
<!--
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.31.0/codemirror.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.31.0/codemirror.min.js"></script>
<style>
  .CodeMirror {
    border: 1px solid #eee;
    height: auto;
  }
</style>
-->

<!--Metatags = preview image when linking to social media-->

<!-- Primary Meta Tags -->
<!-- <title>Mixed Models for Agriculture in R</title> -->
<!-- <meta name="title" content="Mixed Models for Agriculture in R">  -->
<!--
<meta name="description" content="Our aim is to provide a cookbook with mixed model analyses of typical examples in life sciences (focus on agriculture/biology) and compare the possibilities or rather limitations of the R-packages nlme, lme4, glmmTMB and sommer to each other, but also to SAS’ PROC MIXED.">
-->

<!-- Open Graph / Facebook -->
<!--
<meta property="og:type" content="website">
<meta property="og:url" content="https://schmidtpaul.github.io/MMFAIR/index.html">
<meta property="og:title" content="Mixed Models for Agriculture in R">
<meta property="og:description" content="Our aim is to provide a cookbook with mixed model analyses of typical examples in life sciences (focus on agriculture/biology) and compare the possibilities or rather limitations of the R-packages nlme, lme4, glmmTMB and sommer to each other, but also to SAS’ PROC MIXED.">
<meta property="og:image" content="img/logo/ScreenshotIndex.PNG">
-->

<!-- Twitter -->
<!--
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://schmidtpaul.github.io/MMFAIR/index.html">
<meta property="twitter:title" content="Mixed Models for Agriculture in R">
<meta property="twitter:description" content="Our aim is to provide a cookbook with mixed model analyses of typical examples in life sciences (focus on agriculture/biology) and compare the possibilities or rather limitations of the R-packages nlme, lme4, glmmTMB and sommer to each other, but also to SAS’ PROC MIXED.">
<meta property="twitter:image" content="img/logo/ScreenshotIndex.PNG">
-->





<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>
<!-- DEPRECATION-BANNER-START -->
<style>
/* ===== DEPRECATION BANNER ===== */
.deprecation-banner {
    background: linear-gradient(135deg, #c62828, #e53935);
    color: white;
    padding: 24px 24px 18px;
    font-size: 15px;
    line-height: 1.6;
    text-align: center;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    position: relative;
    z-index: 9999;
}
.deprecation-banner strong {
    font-size: 17px;
}
.deprecation-banner .lang-block {
    display: inline-block;
    text-align: center;
    max-width: 600px;
    vertical-align: top;
}
.deprecation-banner .banner-divider {
    display: inline-block;
    width: 1px;
    height: 80px;
    background: rgba(255,255,255,0.4);
    margin: 0 30px;
    vertical-align: middle;
}
.deprecation-banner a.banner-link {
    color: white;
    background: rgba(255,255,255,0.2);
    padding: 6px 16px;
    border-radius: 4px;
    text-decoration: none;
    font-weight: bold;
    border: 1px solid rgba(255,255,255,0.5);
    display: inline-block;
    margin-top: 6px;
    transition: background 0.2s;
}
.deprecation-banner a.banner-link:hover {
    background: rgba(255,255,255,0.35);
}
.deprecation-banner .banner-signature {
    display: block;
    margin-top: 10px;
    font-style: italic;
    font-weight: bold;
    font-size: 17px;
    opacity: 0.9;
}
@media (max-width: 800px) {
    .deprecation-banner .lang-block {
        display: block;
        max-width: 100%;
        margin-bottom: 12px;
    }
    .deprecation-banner .banner-divider {
        display: block;
        width: 60%;
        height: 1px;
        margin: 12px auto;
    }
}
</style>
<div class="deprecation-banner">
    <div class="lang-block">
        <strong>&#9888; Hey, nice that you're here! BUT...</strong><br>
        This site is no longer maintained and may contain outdated information.
        I'm keeping it online because I once promised to never take it down &ndash;
        but I've since built a much better, up-to-date resource. I'd really
        appreciate if you checked it out and found the corresponding chapter there:<br>
        <a class="banner-link" href="https://biomathcontent.netlify.app/">&#10132; biomathcontent.netlify.app</a>
    </div>
    <span class="banner-divider"></span>
    <div class="lang-block">
        <strong>&#9888; Hi, sch&ouml;n, dass du hier bist, ABER...</strong><br>
        Diese Seite wird nicht mehr gepflegt und enth&auml;lt m&ouml;glicherweise
        veraltete Informationen. Ich habe versprochen sie online zu lassen,
        also bleibt sie stehen &ndash; aber alle Inhalte wurden &uuml;berarbeitet,
        verbessert und auf einer neuen Seite zusammengef&uuml;hrt.
        Schau bitte stattdessen dort vorbei:<br>
        <a class="banner-link" href="https://biomathcontent.netlify.app/">&#10132; biomathcontent.netlify.app</a>
    </div>
    <span class="banner-signature">- Cheers, <a href="https://schmidtpaul.github.io/" style="color:white;text-decoration:underline;">Paul</a></span>
</div>
<!-- DEPRECATION-BANNER-END -->



<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">DSFAIR</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Getting Started</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="rbasics.html">R Basics</a>
        </li>
        <li>
          <a href="cor_reg_drinks.html">Correlation &amp; Regression</a>
        </li>
        <li>
          <a href="baddata_outliers_vision.html">Bad Data &amp; Outliers</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Simple Experiments</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="CRD_Mead1993.html">crd_Mead1993</a>
        </li>
        <li>
          <a href="RCBD_ClewerScarisbrick2001.html">rcbd_ClewerScarisbrick2001</a>
        </li>
        <li>
          <a href="latsquare_Bridges1989.html">latsquare_Bridges1989</a>
        </li>
        <li>
          <a href="RCBD_2f_rice.html">rcbd_RCBD_2f_rice</a>
        </li>
        <li>
          <a href="augmented_Pattersen1994.html">augmented_Pattersen1994</a>
        </li>
        <li>
          <a href="alpha_JohnWilliams1995.html">alpha_JohnWilliams1995</a>
        </li>
        <li>
          <a href="rowcol_KemptonFox1997.html">rowcol_KemptonFox1997</a>
        </li>
        <li>
          <a href="splitplot_GomezGomez1984.html">splitplot_GomezGomez1984</a>
        </li>
      </ul>
    </li>
    <li class="dropdown-submenu">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Complex Experiments</a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <a href="subsampling_Piepho1997.html">subsampling_Piepho1997</a>
        </li>
        <li>
          <a href="splitplot_StreetFruit.html">splitplot_StreetFruit</a>
        </li>
        <li>
          <a href="Repeated_RCBD_PiephoEdmondson2018.html">rcbd_PiephoEdmondson2018</a>
        </li>
      </ul>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Summaries
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="compactletterdisplay.html">Compact Letter Display</a>
    </li>
    <li>
      <a href="DesigningExperiments.html">Designing experiments</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://schmidtpaul.github.io/">Contact</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Repeated Measures RCBD</h1>

</div>


<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># the package &quot;mixedup&quot; is not on CRAN, so that you must install</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># it once with the following code:</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>withr<span class="sc">::</span><span class="fu">with_envvar</span>(<span class="fu">c</span>(<span class="at">R_REMOTES_NO_ERRORS_FROM_WARNINGS =</span> <span class="st">&quot;true&quot;</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">&#39;m-clark/mixedup&#39;</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(agriTutorial, tidyverse,  <span class="co"># data import and handling</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>               conflicted, <span class="co"># handle conflicting functions</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>               nlme, glmmTMB, <span class="co"># linear mixed modelling</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>               mixedup, AICcmodavg, car, <span class="co"># linear mixed model processing</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>               emmeans, multcomp, multcompView, <span class="co"># mean comparisons</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>               ggplot2, gganimate, gifski)  <span class="co"># (animated) plots </span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">&quot;select&quot;</span>, <span class="st">&quot;dplyr&quot;</span>) <span class="co"># set select() from dplyr as default</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">conflict_prefer</span>(<span class="st">&quot;filter&quot;</span>, <span class="st">&quot;dplyr&quot;</span>) <span class="co"># set filter() from dplyr as default</span></span></code></pre></div>
<div id="data" class="section level1">
<h1>Data</h1>
<p>The example in this chapter is taken from <a
href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank"><em>Example 4</em> in Piepho &amp; Edmondson (2018)</a>
(see also the <a
href="https://cran.r-project.org/web/packages/agriTutorial/vignettes/agriTutorialVignette.pdf#%5B%7B%22num%22%3A81%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C28.346%2C813.543%2Cnull%5D"
target="_blank">Agritutorial vigniette</a>). It considers data from a
sorghum trial laid out as a randomized complete <code>block</code>
design (5 blocks) with <code>variety</code> (4 sorghum varities) being
the only treatment factor. Thus, we have a total of 20
<code>plot</code>s. It is important to note that our response variable
(<code>y</code>), <strong>the leaf area index, was assessed in five
consecutive weeks on each plot</strong> starting 2 weeks after
emergence. Therefore, the dataset contains a total of 100 values and
what we have here is longitudinal data, <em>a.k.a.</em> repeated
measurements over time, <em>a.k.a.</em> a time series analysis.</p>
<p>As <a
href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank">Piepho &amp; Edmondson (2018)</a> put it: <em>“the week
factor is not a treatment factor that can be randomized. Instead,
repeated measurements are taken on each plot on five consecutive
occasions. Successive measurements on the same plot are likely to be
serially correlated, and this means that for a reliable and efficient
analysis of repeated-measures data we need to take proper account of the
serial correlations between the repeated measures (<a
href="https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1439-037X.2004.00097.x"
target="_blank">Piepho, Büchse &amp; Richter, 2004</a>; <a
href="http://library.mpib-berlin.mpg.de/toc/z2008_18.pdf"
target="_blank">Pinheiro &amp; Bates, 2000</a>).”</em></p>
<p>Please note that this example is also considered on the <a
href="https://schmidtpaul.github.io/MMFAIR/autoregressive_time_series.html"
target="_blank">MMFAIR website</a> but with more focus on how to use the
different mixed model packages to fit the models.</p>
<div id="import-formatting" class="section level2">
<h2>Import &amp; Formatting</h2>
<p>Note that I here decided to give more intuitive names and labels, but
this is optional. We also create a column <code>unit</code> with one
factor level per observation, which will be needed later when using
<code>glmmTMB()</code>.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data - reformatting agriTutorial::sorghum</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> agriTutorial<span class="sc">::</span>sorghum <span class="sc">%&gt;%</span> <span class="co"># data from agriTutorial package</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">block =</span> Replicate, </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">weekF =</span> factweek,  <span class="co"># week as factor</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">weekN =</span> varweek,   <span class="co"># week as numeric/integer</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot  =</span> factplot) <span class="sc">%&gt;%</span> </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variety =</span> <span class="fu">paste0</span>(<span class="st">&quot;var&quot;</span>, variety),    <span class="co"># variety id</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">block   =</span> <span class="fu">paste0</span>(<span class="st">&quot;block&quot;</span>, block),    <span class="co"># block id</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">weekF   =</span> <span class="fu">paste0</span>(<span class="st">&quot;week&quot;</span>, weekF),     <span class="co"># week id</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot    =</span> <span class="fu">paste0</span>(<span class="st">&quot;plot&quot;</span>, plot),      <span class="co"># plot id</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">unit    =</span> <span class="fu">paste0</span>(<span class="st">&quot;obs&quot;</span>, <span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>() )) <span class="sc">%&gt;%</span> <span class="co"># obsevation id</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_at</span>(<span class="fu">vars</span>(variety<span class="sc">:</span>plot, unit), as.factor) <span class="sc">%&gt;%</span> </span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>()</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>dat</span></code></pre></div>
<pre><code>## # A tibble: 100 × 8
##        y variety block  weekF plot  weekN varblock unit 
##    &lt;dbl&gt; &lt;fct&gt;   &lt;fct&gt;  &lt;fct&gt; &lt;fct&gt; &lt;int&gt;    &lt;int&gt; &lt;fct&gt;
##  1  5    var1    block1 week1 plot1     1        1 obs1 
##  2  4.84 var1    block1 week2 plot1     2        1 obs2 
##  3  4.02 var1    block1 week3 plot1     3        1 obs3 
##  4  3.75 var1    block1 week4 plot1     4        1 obs4 
##  5  3.13 var1    block1 week5 plot1     5        1 obs5 
##  6  4.42 var1    block2 week1 plot2     1        2 obs6 
##  7  4.3  var1    block2 week2 plot2     2        2 obs7 
##  8  3.67 var1    block2 week3 plot2     3        2 obs8 
##  9  3.23 var1    block2 week4 plot2     4        2 obs9 
## 10  2.83 var1    block2 week5 plot2     5        2 obs10
## # … with 90 more rows</code></pre>
</div>
<div id="exploring" class="section level2">
<h2>Exploring</h2>
<p>In order to obtain a field layout of the trial, we would like use the
<code>desplot()</code> function. Notice that for this we need two data
columns that identify the <code>row</code> and <code>col</code> of each
plot in the trial. These are unfortunately not given here, so that we
cannot create the actual field layout plot.</p>
<div id="descriptive-tables" class="section level3">
<h3>descriptive tables</h3>
<p>We could also have a look at the arithmetic means and standard
deviations for yield per <code>variety</code>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(variety) <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean    =</span> <span class="fu">mean</span>(y, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">std.dev =</span> <span class="fu">sd</span>(y, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean)) <span class="sc">%&gt;%</span> <span class="co"># sort</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n=</span><span class="cn">Inf</span>) <span class="co"># print full table</span></span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   variety  mean std.dev
##   &lt;fct&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1 var3     4.63   0.757
## 2 var4     4.61   0.802
## 3 var2     4.59   0.763
## 4 var1     3.50   0.760</code></pre>
<p>Furthermore, we could look at the arithmetic means for each week as
follows:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>dat <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(weekF, variety) <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean =</span> <span class="fu">mean</span>(y, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> weekF, <span class="at">values_from =</span> mean)  </span></code></pre></div>
<pre><code>## # A tibble: 4 × 6
##   variety week1 week2 week3 week4 week5
##   &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 var1     4.24  4.05  3.41  3.09  2.7 
## 2 var2     5.15  4.98  4.59  4.22  4.01
## 3 var3     4.89  5.07  4.71  4.48  4.02
## 4 var4     5.15  4.94  4.71  4.39  3.83</code></pre>
</div>
<div id="descriptive-plot" class="section level3">
<h3>descriptive plot</h3>
<p>We can also create a plot to get a better feeling for the data. Note
that here we could even decide to extend the ggplot to become an
animated gif as follows:</p>
<div class="sourceCode" id="cb8"><pre
class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>var_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;#8cb369&quot;</span>, <span class="st">&quot;#f4a259&quot;</span>, <span class="st">&quot;#5b8e7d&quot;</span>, <span class="st">&quot;#bc4b51&quot;</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(var_colors) <span class="ot">&lt;-</span> dat<span class="sc">$</span>variety <span class="sc">%&gt;%</span> <span class="fu">levels</span>()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>gganimate_plot <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat, <span class="fu">aes</span>(<span class="at">y =</span> y, <span class="at">x =</span> weekF,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">group =</span> variety,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">color =</span> variety)) <span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Leaf area index&quot;</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">6.5</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> var_colors) <span class="sc">+</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, </span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>()) <span class="sc">+</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transition_time</span>(weekN) <span class="sc">+</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shadow_mark</span>(<span class="at">exclude_layer =</span> <span class="dv">2</span>) </span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="fu">animate</span>(gganimate_plot, <span class="at">renderer =</span> <span class="fu">gifski_renderer</span>()) <span class="co"># render gif</span></span></code></pre></div>
<p><img
src="Repeated_RCBD_PiephoEdmondson2018_files/figure-html/unnamed-chunk-6-1.gif" /><!-- --></p>
</div>
</div>
</div>
<div id="model-building" class="section level1">
<h1>Model building</h1>
<p>Our goal is therefore to build a suitable model taking serial
correlation into account. In order to do this, we will initially
consider the model for a single time point. Then, we extend this model
to account for multiple weeks by allowing for week-speficic effects.
Finally, we further allow for serially correlated error terms.</p>
<div id="single-week" class="section level2">
<h2>Single week</h2>
<p>When looking at data from a single time point (<em>e.g.</em> the
first week), we merely have 20 observations from a randomized complete
block design with a single treatment factor. It can therefore be
analyzed with a simple one-way ANOVA (fixed <code>variety</code> effect)
for randomized complete block designs (fixed <code>block</code>
effect):</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>dat.wk1 <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">filter</span>(weekF <span class="sc">==</span> <span class="st">&quot;week1&quot;</span>) <span class="co"># subset data from first week only</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>mod.wk1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> y <span class="sc">~</span> variety <span class="sc">+</span> block,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> dat.wk1)</span></code></pre></div>
<p>We could now go on and look at the ANOVA via
<code>anova(mod.wk1)</code> and it would indeed not be <em>wrong</em> to
simply repeat this for each week. Yet, one may not be satisfied with
obtaining multiple ANOVA results - namely one per week. This is
especially likeliy in case the results contradict each other, because
<em>e.g.</em> the variety effects are found to be significant in only
two out of five weeks. Therefore, one may want to analyze the entire
dataset <em>i.e.</em> the multiple weeks jointly.</p>
</div>
<div id="multiple-weeks-mw" class="section level2">
<h2>Multiple weeks (MW)</h2>
<p>Going from the single-week-analysis to jointly analyzing the entire
dataset is more than just changing the <code>data =</code> statement in
the model. This is because <em>“it is realistic to assume that the
treatment effects evolve over time and thus are week-specific.
Importantly, we must also allow for the block effects to change over
time in an individual manner. For example, there could be fertility or
soil type differences between blocks and these could have a smooth
progressive or cumulative time-based effect on differences between the
blocks dependent on factors such as temperature or rainfall”</em> <a
href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank">(Piepho &amp; Edmondson, 2018)</a>. We implement this by
taking the model in <code>mod.wk1</code> and multipyling each effect
with <code>week</code>. Note that this is also true for the general
interecept (µ) in <code>mod.wk1</code>, meaning that we would like to
include one intercept per week, which can be achieved by simply adding
<code>week</code> as a main effect as well. This leaves us with fixed
main effects for <code>week</code>, <code>variety</code>, and
<code>block</code>, as well as the week-specific effects of the latter
two <code>week:variety</code> and <code>week:block</code>.</p>
<p>Finally, note that we are not doing anything about the model’s error
term at this point. More specifically this means that its variance
structure is still the default <strong>iid</strong> (independent and
identically distributed) - see <a href="variance_structures.html"
target="_blank">the summary on correlation/variance strucutres at the
MMFAIR website</a>.</p>
<blockquote>
<p>I decide to use the <code>glmmTMB</code> package to fit the linear
models here, because I feel that their syntax is more intuitive. Note
that one may also use the <code>nlme</code> package to do this, just as
<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank">(Piepho &amp; Edmondson, 2018)</a> did and you can find
a direct comparison of the R syntax with additional information <a
href="https://schmidtpaul.github.io/MMFAIR/autoregressive_time_series.html#nlme-1"
target="_blank">in the MMFAIR chapter</a>.</p>
</blockquote>
</div>
<div id="mw---indepentent-errors"
class="section level2 tabset tabset-fade">
<h2 class="tabset tabset-fade">MW - indepentent errors</h2>
<div id="glmmtmb" class="section level3">
<h3>glmmTMB</h3>
<p>With the <code>glmmTMB()</code> function, it is possible to</p>
<ol style="list-style-type: decimal">
<li>fix the error variance to 0 via adding the
<code>dispformula = ~ 0</code> argument and then</li>
<li>mimic the error (variance) as a random effect (variance) via the
<code>unit</code> column with different entries for each data
point.</li>
</ol>
<p>While this may not be necessary for this model with the default
homoscedastic, independent error variance structure, using it here will
allow for an intuitve comparison to the following model with more
sophisticated variance structures.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>mod.iid <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(<span class="at">formula =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (variety <span class="sc">+</span> block) </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> unit),      <span class="co"># add random unit term to mimic error variance</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="co"># fix original error variance to 0</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">REML =</span> <span class="cn">TRUE</span>,       <span class="co"># needs to be stated since default = ML</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> dat) </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance component estimates</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative: mod.iid %&gt;% broom.mixed::tidy(effects = &quot;ran_pars&quot;, scales = &quot;vcov&quot;)</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>mod.iid <span class="sc">%&gt;%</span> mixedup<span class="sc">::</span><span class="fu">extract_vc</span>(<span class="at">ci_scale =</span> <span class="st">&quot;var&quot;</span>) </span></code></pre></div>
<pre><code>## # A tibble: 2 × 7
##   group    effect    variance    sd var_2.5 var_97.5 var_prop
##   &lt;chr&gt;    &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 unit     Intercept    0.023 0.152   0.016    0.033        1
## 2 Residual &lt;NA&gt;         0     0      NA       NA            0</code></pre>
<p>As expected, we find the residual variance to be 0 and instead we
have the mimiced homoscedastic, independent error variance for the
random <code>(1 | unit)</code> effect estimated as 0.023.</p>
</div>
<div id="nlme" class="section level3">
<h3>nlme</h3>
<p>Since the models in this chapter do not contain any random effects,
we make use of <code>gls()</code> instead of <code>lme()</code>.
Furthermore, we specifically write out the
<code>correlation = NULL</code> argument to get a homoscedastic,
independent error variance structure. While this may not be necessary
because it is the default, using it here will allow for an intuitve
comparison to the following models with more sophisticated variance
structures.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mod.iid.nlme <span class="ot">&lt;-</span> <span class="fu">gls</span>(<span class="at">model =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (block <span class="sc">+</span> variety), </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">correlation =</span> <span class="cn">NULL</span>, <span class="co"># default, i.e. homoscedastic, independent errors</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> dat)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance component estimates</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">varstruct =</span> <span class="st">&quot;iid&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sigma    =</span> mod.iid.nlme<span class="sc">$</span>sigma) <span class="sc">%&gt;%</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Variance =</span> sigma<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   varstruct sigma Variance
##   &lt;chr&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 iid       0.152   0.0232</code></pre>
<p>It can be seen that the residual homoscedastic, independent error
variance was estimated as 0.023.</p>
</div>
</div>
<div id="mw---autocorrelated-errors"
class="section level2 tabset tabset-fade tabset-pills">
<h2 class="tabset tabset-fade tabset-pills">MW - autocorrelated
errors</h2>
<p>Note that at this point of the analysis, the model above with an
independent, homogeneous error term above is neither the right, nor the
wrong choice. It must be clear that <em>“measurements on the same plot
are <strong>likely</strong> to be serially correlated”</em>. Thus, it
should be investigated whether any covariance structure for the error
term (instead of the default independence between errors) is more
appropriate to model this dataset. It could theoretically be the case
that this <code>mod.iid</code> is the best choice here, but we cannot
confirm this yet, as we have not looked at any alternatives. This is
what we will do in the next step.</p>
<blockquote>
<p>One may ask <strong>at what step of the analysis it is best to
compare and find the appropriate covariance structure for the error
term</strong> in such a scenario. It is indeed here, at this step. As <a
href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank">Piepho &amp; Edmondson (2018)</a> write:
<em>“<strong>Before modelling the treatment effect</strong>, a
variance–covariance model needs to be identified for these correlations.
This is best done by using a saturated model for treatments and time,
i.e., a model that considers all treatment factors and time as
qualitative.”</em> Note that this <em>saturated model</em> is what we
have in <code>mod.iid</code>. So in short: one should compare variance
structures for the error term <strong>before</strong> running an ANOVA /
conducting model selection steps.</p>
</blockquote>
<p>Units on which repeated observations are taken are often referred to
as subjects. We would now like to allow measurements taken on the same
subjects (plot in this case) to be serially correlated, while
observations on different subjects are still considered independent.
More specifically, we want the errors of the respective observations to
be correlated in our model.
<img src="img/corrvalues.PNG" style="width:60%; margin-right: 10px" align="left"></p>
<p>Take the visualisation on the left depicting a subset of our data.
Here, you can see plots 1 and 2 (out of the total of 20 in our dataset)
side by side. Furthermore, they are shown for weeks 1-3 (out of the
total of 5 in our dataset). Thus, a total of six values are represented,
coming from only two subjects/plots, but obtained in three different
weeks. The blue arrows represent correlation among errors. For these six
measurements, there are six blue arrows, since there are six error pairs
that come from the same plot, respectively. The green lines on the other
hand represent error pairs that do not come from the same plot and thus
are assumed to be independent. Finally, notice that the errors coming
from the same plot, but with two instead of just one week between their
measurements, are shown in a lighter blue. This is because one may
indeed assume a weaker correlation between errors that are further apart
in terms of time passed between measurements.</p>
<p>The latter can be achieved by using a correlation structure for
repeated measures over time. Maybe most popular correlation structure is
called <strong>first order autoregressive AR(1)</strong>. It should be
noted that this correlation structure is useful, if all time points are
equally spaced, which is the case here, as there is always exactly one
week between consecutive time points. As can be seen in the analysis of
<a href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank"><em>Example 4</em> in Piepho &amp; Edmondson (2018)</a>
and the corresponding <a
href="https://cran.r-project.org/web/packages/agriTutorial/vignettes/agriTutorialVignette.pdf#%5B%7B%22num%22%3A81%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C28.346%2C813.543%2Cnull%5D"
target="_blank">Agritutorial vigniette</a>, however, there are more
options that just AR(1). Therefore, we will also try out multiple
variance structures to model the serial correlation of our longitudinal
data.</p>
<div id="ar1" class="section level3 tabset tabset-fade">
<h3 class="tabset tabset-fade">AR(1)</h3>
<div id="glmmtmb-1" class="section level4">
<h4>glmmTMB</h4>
<p>To model the variance structure of our mimiced error term as first
order autoregressive, we replace the <code>(1 | unit)</code> from the
<code>iid</code> model with <code>ar1(weekF + 0 | plot)</code>. As can
be seen, subjects are identified after the <code>|</code> and the
variance structure in this syntax.</p>
<p>Note that by adding the <code>show_cor = TRUE</code> argument to the
<code>extract_vc</code> function, we obtain two outputs: The variance
component estimates, as seen above for the <code>iid</code> model, as
well as the correlation matrix / variance structure for a single
plot.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mod.AR1 <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(<span class="at">formula =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (variety <span class="sc">+</span> block) <span class="sc">+</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">ar1</span>(weekF <span class="sc">+</span> <span class="dv">0</span> <span class="sc">|</span> plot), <span class="co"># ar1 structure as random term to mimic error var</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="co"># fix original error variance to 0</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">REML =</span> <span class="cn">TRUE</span>,       <span class="co"># needs to be stated since default = ML</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> dat) </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance component estimates</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative: mod.ar1 %&gt;% broom.mixed::tidy(effects = &quot;ran_pars&quot;, scales = &quot;vcov&quot;)</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>mod.AR1 <span class="sc">%&gt;%</span> <span class="fu">extract_vc</span>(<span class="at">ci_scale =</span> <span class="st">&quot;var&quot;</span>, <span class="at">show_cor =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>## $`Variance Components`
## # A tibble: 2 × 6
##   group    variance    sd var_2.5 var_97.5 var_prop
##   &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 plot        0.022 0.149   0.013    0.038      0.2
## 2 Residual    0     0      NA       NA          0  
## 
## $Cor
## $Cor$plot
##            weekFweek1 weekFweek2 weekFweek3 weekFweek4 weekFweek5
## weekFweek1      1.000      0.749      0.561      0.420      0.315
## weekFweek2      0.749      1.000      0.749      0.561      0.420
## weekFweek3      0.561      0.749      1.000      0.749      0.561
## weekFweek4      0.420      0.561      0.749      1.000      0.749
## weekFweek5      0.315      0.420      0.561      0.749      1.000</code></pre>
<p>We can see that the we get <span
class="math inline">\(\sigma^2_{plot} =\)</span> <code>0.022</code> and
a <span class="math inline">\(\rho =\)</span> <code>0.749</code>.</p>
</div>
<div id="nlme-1" class="section level4">
<h4>nlme</h4>
<p>In <code>nlme</code> we make use of the <code>correlation =</code>
argument and use the <code>corAR1</code> <a
href="https://cran.r-project.org/web/packages/nlme/nlme.pdf#Rfn.corClasses.1"
target="_blank">correlation strucutre class</a>. In its syntax, subjects
are identified after the <code>|</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>mod.AR1.nlme <span class="ot">&lt;-</span> <span class="fu">gls</span>(<span class="at">model =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (block <span class="sc">+</span> variety),</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">correlation =</span> <span class="fu">corAR1</span>(<span class="at">form =</span> <span class="sc">~</span> weekN <span class="sc">|</span> plot),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> dat)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance component estimates</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">varstruct =</span> <span class="st">&quot;ar(1)&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sigma    =</span> mod.AR1.nlme<span class="sc">$</span>sigma,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">rho      =</span> <span class="fu">coef</span>(mod.AR1.nlme<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct, <span class="at">unconstrained =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Variance =</span> sigma<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr1wk  =</span> rho,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr2wks =</span> rho<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr3wks =</span> rho<span class="sc">^</span><span class="dv">3</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr4wks =</span> rho<span class="sc">^</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   varstruct sigma   rho Variance Corr1wk Corr2wks Corr3wks Corr4wks
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 ar(1)     0.149 0.749   0.0222   0.749    0.561    0.420    0.315</code></pre>
<p>We can see that the we get <span
class="math inline">\(\sigma^2_{plot} =\)</span> <code>0.022</code> and
a <span class="math inline">\(\rho =\)</span> <code>0.749</code>.</p>
</div>
<div id="nlme-v2" class="section level4">
<h4>nlme V2</h4>
<p>For completeness, I want to show that the same model can also be fit
in <code>nlme</code> via the <code>corExp</code> <a
href="https://cran.r-project.org/web/packages/nlme/nlme.pdf#Rfn.corClasses.1"
target="_blank">correlation strucutre class</a>. Note that this was
actually done in the <a
href="https://cran.r-project.org/web/packages/agriTutorial/vignettes/agriTutorialVignette.pdf#%5B%7B%22num%22%3A81%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C28.346%2C813.543%2Cnull%5D"
target="_blank">Agritutorial vigniette</a> and <a
href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank">Piepho &amp; Edmondson (2018)</a> write in Appendix 2:
“Initially, we used corCAR1() to fit the model correlation structure but
subsequently found that corExp() was more flexible as it allowed the
inclusion of a “nugget” term, which seemingly cannot be done with
corCAR1(). We note that it is essential that the variable weeks in the
specification of the correlation structure, corr = corExp (form =
~weeks|Plots), is a numeric variable with values representing the time
values of the repeated measurements. Note that this code will also work
for repeated observations that are not necessarily equally spaced. It is
also necessary that each plot has a unique level for the variable
Plots.”</p>
<p>Notice also that the increased flexibility comes at a price:
Extracting the estimate for <span class="math inline">\(\rho\)</span>
takes quite some code:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mod.AR1.nlme.V2 <span class="ot">&lt;-</span> <span class="fu">gls</span>(<span class="at">model =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (variety <span class="sc">+</span> block),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">correlation =</span> <span class="fu">corExp</span>(<span class="at">form =</span> <span class="sc">~</span> weekN <span class="sc">|</span> plot),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> dat)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">varstruct =</span> <span class="st">&quot;ar(1)&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sigma    =</span> mod.AR1.nlme.V2<span class="sc">$</span>sigma,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">rho      =</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="fu">coef</span>(mod.AR1.nlme.V2<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct, </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">unconstrained =</span> <span class="cn">FALSE</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Variance =</span> sigma<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr1wk  =</span> rho,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr2wks =</span> rho<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr3wks =</span> rho<span class="sc">^</span><span class="dv">3</span>,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr4wks =</span> rho<span class="sc">^</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   varstruct sigma   rho Variance Corr1wk Corr2wks Corr3wks Corr4wks
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 ar(1)     0.149 0.749   0.0222   0.749    0.561    0.420    0.315</code></pre>
<p>We can see that the we get <span
class="math inline">\(\sigma^2_{plot} =\)</span> <code>0.022</code> and
a <span class="math inline">\(\rho =\)</span> <code>0.749</code>.</p>
</div>
</div>
<div id="ar1-nugget" class="section level3 tabset tabset-fade">
<h3 class="tabset tabset-fade">AR(1) + nugget</h3>
<div id="glmmtmb-2" class="section level4">
<h4>glmmTMB</h4>
<p></br></br></br></p>
<p><span style="color:red"> not possible ?</span></p>
<p></br></br></br></p>
<div class="sourceCode" id="cb20"><pre
class="sourceCode r fold-hide"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mod.AR1nugget <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(<span class="at">formula =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (variety <span class="sc">+</span> block) <span class="sc">+</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">ar1</span>(weekF <span class="sc">+</span> <span class="dv">0</span> <span class="sc">|</span> plot), <span class="co"># ar1 structure as random term to mimic error var</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                         <span class="co"># dispformula = ~ 0, # error variance allowed = nugget!</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">REML =</span> <span class="cn">TRUE</span>,       <span class="co"># needs to be stated since default = ML</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> dat) </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># show variance components</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative: mod.AR1nugget %&gt;% broom.mixed::tidy(effects = &quot;ran_pars&quot;, scales = &quot;vcov&quot;)</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>mod.AR1nugget <span class="sc">%&gt;%</span> <span class="fu">extract_vc</span>(<span class="at">ci_scale =</span> <span class="st">&quot;var&quot;</span>, <span class="at">show_cor =</span> <span class="cn">TRUE</span>) </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co"># We can see that the we get $\sigma^2_{plot} =$ `0.019`, an additional residual/nugget variance  $\sigma^2_{N} =$ `0.004` and a $\rho =$ of `0.908`.</span></span></code></pre></div>
</div>
<div id="nlme-2" class="section level4">
<h4>nlme</h4>
<p>As pointed out by <a
href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank">Piepho &amp; Edmondson (2018)</a> write in Appendix 2:
“Initially, we used corCAR1() to fit the model correlation structure but
subsequently found that corExp() was more flexible as it allowed the
inclusion of a “nugget” term, which seemingly cannot be done with
corCAR1(). We note that it is essential that the variable weeks in the
specification of the correlation structure, corr = corExp (form =
~weeks|Plots), is a numeric variable with values representing the time
values of the repeated measurements. Note that this code will also work
for repeated observations that are not necessarily equally spaced. It is
also necessary that each plot has a unique level for the variable
Plots.” This was also done in the <a
href="https://cran.r-project.org/web/packages/agriTutorial/vignettes/agriTutorialVignette.pdf#%5B%7B%22num%22%3A81%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C28.346%2C813.543%2Cnull%5D"
target="_blank">Agritutorial vigniette</a>.</p>
<p>Notice also that the increased flexibility comes at a price:
Extracting the estimate for <span class="math inline">\(\rho\)</span>
takes quite some code:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>mod.AR1nugget.nlme <span class="ot">&lt;-</span> <span class="fu">gls</span>(<span class="at">model =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (block <span class="sc">+</span> variety),</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">correlation =</span> <span class="fu">corExp</span>(<span class="at">form =</span> <span class="sc">~</span> weekN <span class="sc">|</span> plot, <span class="at">nugget =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data =</span> dat)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">varstruct =</span> <span class="st">&quot;ar(1) + nugget&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sigma    =</span> mod.AR1nugget.nlme<span class="sc">$</span>sigma,</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">nugget   =</span> <span class="fu">coef</span>(mod.AR1nugget.nlme<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct, </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">unconstrained =</span> <span class="cn">FALSE</span>)[<span class="dv">2</span>],</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">rho      =</span> (<span class="dv">1</span><span class="sc">-</span><span class="fu">coef</span>(mod.AR1nugget.nlme<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct, </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>                            <span class="at">unconstrained =</span> <span class="cn">FALSE</span>)[<span class="dv">2</span>])<span class="sc">*</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">exp</span>(<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="fu">coef</span>(mod.AR1nugget.nlme<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct, </span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>                                <span class="at">unconstrained =</span> <span class="cn">FALSE</span>)[<span class="dv">1</span>])) <span class="sc">%&gt;%</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Variance =</span> sigma<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr1wk  =</span> rho,</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr2wks =</span> rho<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr3wks =</span> rho<span class="sc">^</span><span class="dv">3</span>,</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr4wks =</span> rho<span class="sc">^</span><span class="dv">4</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 9
##   varstruct      sigma nugget   rho Variance Corr1wk Corr2wks Corr3wks Corr4wks
##   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 ar(1) + nugget 0.150  0.172 0.752   0.0225   0.752    0.565    0.425    0.319</code></pre>
<p>We can see that the we get <span
class="math inline">\(\sigma^2_{plot} =\)</span> <code>0.0225</code> and
a <span class="math inline">\(\rho =\)</span> <code>0.752</code>.</p>
</div>
</div>
<div id="cs" class="section level3 tabset tabset-fade">
<h3 class="tabset tabset-fade">CS</h3>
<div id="glmmtmb-hcs" class="section level4">
<h4>glmmTMB (hCS!)</h4>
<p><strong>Note that <code>glmmTMB()</code> only allows for
heterogengeous compound symmetry and not standard compound
symmetry!</strong></p>
<p>To model the variance structure of our mimiced error term as a
heterogeneous compound symmetry structure, we use
<code>cs(weekF + 0 | plot)</code>. Notice that this is not the simple
compound symmetry structure that <a
href="https://onlinelibrary.wiley.com/doi/full/10.1111/jac.12267"
target="_blank">Piepho &amp; Edmondson (2018)</a> applied, because
<code>glmmTMB()</code> only allows for heterogeneous compound symmetry
at the moment.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mod.hCS <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(<span class="at">formula =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (variety <span class="sc">+</span> block) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">cs</span>(weekF <span class="sc">+</span> <span class="dv">0</span> <span class="sc">|</span> plot), <span class="co"># hcs structure as random term to mimic error var</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="co"># fix original error variance to 0</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">REML =</span> <span class="cn">TRUE</span>,       <span class="co"># needs to be stated since default = ML</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> dat) </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># show variance components</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative: mod.hCS %&gt;% broom.mixed::tidy(effects = &quot;ran_pars&quot;, scales = &quot;vcov&quot;)</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>mod.hCS <span class="sc">%&gt;%</span> <span class="fu">extract_vc</span>(<span class="at">ci_scale =</span> <span class="st">&quot;var&quot;</span>, <span class="at">show_cor =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>## $`Variance Components`
## # A tibble: 6 × 7
##   group    effect     variance    sd var_2.5 var_97.5 var_prop
##   &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 plot     weekFweek1    0.021 0.144   0.009    0.046    0.181
## 2 plot     weekFweek2    0.022 0.147   0.01     0.048    0.188
## 3 plot     weekFweek3    0.021 0.146   0.01     0.047    0.186
## 4 plot     weekFweek4    0.029 0.171   0.014    0.063    0.254
## 5 plot     weekFweek5    0.022 0.148   0.01     0.049    0.191
## 6 Residual &lt;NA&gt;          0     0      NA       NA        0    
## 
## $Cor
## $Cor$plot
##            weekFweek1 weekFweek2 weekFweek3 weekFweek4 weekFweek5
## weekFweek1      1.000      0.702      0.702      0.702      0.702
## weekFweek2      0.702      1.000      0.702      0.702      0.702
## weekFweek3      0.702      0.702      1.000      0.702      0.702
## weekFweek4      0.702      0.702      0.702      1.000      0.702
## weekFweek5      0.702      0.702      0.702      0.702      1.000</code></pre>
<p>We can see that the we get heterogeneous <span
class="math inline">\(\sigma^2_{plot}\)</span> estimates per week:
<code>0.021</code>, <code>0.022</code>, <code>0.021</code>,
<code>0.029</code>, <code>0.022</code> and a <span
class="math inline">\(\rho =\)</span> <code>0.702</code>.</p>
</div>
<div id="nlme-3" class="section level4">
<h4>nlme</h4>
<p>In <code>nlme</code> we make use of the <code>correlation =</code>
argument and use the <code>corCompSymm</code> <a
href="https://cran.r-project.org/web/packages/nlme/nlme.pdf#Rfn.corClasses.1"
target="_blank">correlation strucutre class</a>. In its syntax, subjects
are identified after the <code>|</code>.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>mod.CS.nlme <span class="ot">&lt;-</span> <span class="fu">gls</span>(y <span class="sc">~</span> weekF <span class="sc">*</span> (block <span class="sc">+</span> variety),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">corr =</span> <span class="fu">corCompSymm</span>(<span class="at">form =</span> <span class="sc">~</span> weekN <span class="sc">|</span> plot),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> dat)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">varstruct =</span> <span class="st">&quot;cs&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sigma    =</span> mod.CS.nlme<span class="sc">$</span>sigma,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">rho      =</span> <span class="fu">coef</span>(mod.CS.nlme<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct, <span class="at">unconstrained =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Variance =</span> sigma<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr1wk  =</span> rho,</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr2wks =</span> rho,</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr3wks =</span> rho,</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Corr4wks =</span> rho)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 8
##   varstruct sigma   rho Variance Corr1wk Corr2wks Corr3wks Corr4wks
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 cs        0.152 0.701   0.0232   0.701    0.701    0.701    0.701</code></pre>
<p>We can see that the we get <span
class="math inline">\(\sigma^2_{plot} =\)</span> <code>0.023</code> and
a <span class="math inline">\(\rho =\)</span> of <code>0.701</code>.</p>
</div>
</div>
<div id="toeplitz" class="section level3 tabset tabset-fade">
<h3 class="tabset tabset-fade">Toeplitz</h3>
<div id="glmmtmb-3" class="section level4">
<h4>glmmTMB</h4>
<p>To model the variance structure of our mimiced error term as a
toeplitz structure, we use <code>toep(weekF + 0 | plot)</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>mod.Toep <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(<span class="at">formula =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (variety <span class="sc">+</span> block) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">toep</span>(weekF <span class="sc">+</span> <span class="dv">0</span> <span class="sc">|</span> plot), <span class="co"># teop structure as random term to mimic err var</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="co"># fix original error variance to 0</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">REML =</span> <span class="cn">TRUE</span>,       <span class="co"># needs to be stated since default = ML</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> dat) </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co"># show variance components</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative: mod.Toep %&gt;% broom.mixed::tidy(effects = &quot;ran_pars&quot;, scales = &quot;vcov&quot;)</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>mod.Toep <span class="sc">%&gt;%</span> <span class="fu">extract_vc</span>(<span class="at">ci_scale =</span> <span class="st">&quot;var&quot;</span>, <span class="at">show_cor =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>## $`Variance Components`
## # A tibble: 6 × 7
##   group    effect     variance    sd var_2.5 var_97.5 var_prop
##   &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 plot     weekFweek1    0.021 0.144   0.009    0.046    0.182
## 2 plot     weekFweek2    0.023 0.152   0.01     0.052    0.202
## 3 plot     weekFweek3    0.022 0.147   0.01     0.048    0.19 
## 4 plot     weekFweek4    0.029 0.17    0.013    0.062    0.253
## 5 plot     weekFweek5    0.02  0.141   0.009    0.043    0.174
## 6 Residual &lt;NA&gt;          0     0      NA       NA        0    
## 
## $Cor
## $Cor$plot
##            weekFweek1 weekFweek2 weekFweek3 weekFweek4 weekFweek5
## weekFweek1      1.000      0.764      0.691      0.637      0.552
## weekFweek2      0.764      1.000      0.764      0.691      0.637
## weekFweek3      0.691      0.764      1.000      0.764      0.691
## weekFweek4      0.637      0.691      0.764      1.000      0.764
## weekFweek5      0.552      0.637      0.691      0.764      1.000</code></pre>
<p>We can see that the we get heterogeneous <span
class="math inline">\(\sigma^2_{plot}\)</span> estimates per week:
<code>0.021</code>, <code>0.023</code>, <code>0.022</code>,
<code>0.029</code>, <code>0.020</code> and a heterogeneous <span
class="math inline">\(\rho\)</span> per week-difference:
<code>0.764</code>, <code>0.691</code>, <code>0.637</code> and
<code>0.552</code>.</p>
</div>
<div id="nlme-4" class="section level4">
<h4>nlme</h4>
<p></br></br></br></p>
<p><span style="color:red"> not possible? At least it is not included in
the agriTutorial vigniette and there is no obviously corresponding
cor.class found in the nlme documentation. </span></p>
<p></br></br></br></p>
</div>
</div>
<div id="un" class="section level3 tabset tabset-fade">
<h3 class="tabset tabset-fade">UN</h3>
<div id="glmmtmb-4" class="section level4">
<h4>glmmTMB</h4>
<p>To model the variance structure of our mimiced error term as a
completely unstrucutred variance structure, we use
<code>us(weekF + 0 | plot)</code>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>mod.UN <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(<span class="at">formula =</span> y <span class="sc">~</span> weekF <span class="sc">*</span> (variety <span class="sc">+</span> block) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">us</span>(weekF <span class="sc">+</span> <span class="dv">0</span> <span class="sc">|</span> plot), <span class="co"># us structure as random term to mimic error var</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">dispformula =</span> <span class="sc">~</span> <span class="dv">0</span>, <span class="co"># fix original error variance to 0</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">REML =</span> <span class="cn">TRUE</span>,       <span class="co"># needs to be stated since default = ML</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> dat) </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># show variance components</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative: mod.UN %&gt;% broom.mixed::tidy(effects = &quot;ran_pars&quot;, scales = &quot;vcov&quot;)</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>mod.UN <span class="sc">%&gt;%</span> <span class="fu">extract_vc</span>(<span class="at">ci_scale =</span> <span class="st">&quot;var&quot;</span>, <span class="at">show_cor =</span> <span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>## $`Variance Components`
## # A tibble: 6 × 7
##   group    effect     variance    sd var_2.5 var_97.5 var_prop
##   &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 plot     weekFweek1    0.02  0.141   0.009    0.044    0.17 
## 2 plot     weekFweek2    0.021 0.143   0.009    0.046    0.177
## 3 plot     weekFweek3    0.022 0.149   0.01     0.05     0.192
## 4 plot     weekFweek4    0.033 0.181   0.015    0.073    0.282
## 5 plot     weekFweek5    0.021 0.143   0.009    0.046    0.178
## 6 Residual &lt;NA&gt;          0     0      NA       NA        0    
## 
## $Cor
## $Cor$plot
##            weekFweek1 weekFweek2 weekFweek3 weekFweek4 weekFweek5
## weekFweek1      1.000      0.708      0.644      0.748      0.534
## weekFweek2      0.708      1.000      0.634      0.744      0.549
## weekFweek3      0.644      0.634      1.000      0.934      0.718
## weekFweek4      0.748      0.744      0.934      1.000      0.776
## weekFweek5      0.534      0.549      0.718      0.776      1.000</code></pre>
<p>As can be seen, each week <em>gets its own</em> variance and also
each pair of weeks <em>gets</em> individual correlations.</p>
</div>
<div id="nlme-5" class="section level4">
<h4>nlme</h4>
<p>In <code>nlme</code> we make use of the <code>correlation =</code>
argument and use the <code>corSymm</code> <a
href="https://cran.r-project.org/web/packages/nlme/nlme.pdf#Rfn.corClasses.1"
target="_blank">correlation strucutre class</a> in combination with the
<a
href="https://cran.r-project.org/web/packages/nlme/nlme.pdf#Rfn.varIdent.1"
target="_blank"><code>varIdent()</code></a> in the <a
href="https://cran.r-project.org/web/packages/nlme/nlme.pdf#Rfn.lme.1"
target="_blank"><code>weights=</code></a> argument, which is <em>used to
allow for different variances according to the levels of a
classification factor</em>. In its syntax, subjects are identified after
the <code>|</code>.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>mod.UN.nlme <span class="ot">&lt;-</span> <span class="fu">gls</span>(y <span class="sc">~</span> weekF <span class="sc">*</span> (block <span class="sc">+</span> variety), </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">corr =</span> <span class="fu">corSymm</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> plot), </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">weights =</span> <span class="fu">varIdent</span>(<span class="at">form =</span> <span class="sc">~</span> <span class="dv">1</span><span class="sc">|</span>weekF), </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> dat)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance component estimates: variances</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>mod.UN.nlme<span class="sc">$</span>modelStruct<span class="sc">$</span>varStruct <span class="sc">%&gt;%</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(<span class="at">unconstrained =</span> <span class="cn">FALSE</span>, <span class="at">allCoef =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">enframe</span>(<span class="at">name =</span> <span class="st">&quot;grp&quot;</span>, <span class="at">value =</span> <span class="st">&quot;varStruct&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sigma         =</span> mod.UN.nlme<span class="sc">$</span>sigma) <span class="sc">%&gt;%</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">StandardError =</span> sigma <span class="sc">*</span> varStruct) <span class="sc">%&gt;%</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Variance      =</span> StandardError <span class="sc">^</span> <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 5
##   grp   varStruct sigma StandardError Variance
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;
## 1 week1      1    0.141         0.141   0.0197
## 2 week2      1.02 0.141         0.143   0.0206
## 3 week3      1.06 0.141         0.149   0.0223
## 4 week4      1.29 0.141         0.181   0.0327
## 5 week5      1.02 0.141         0.143   0.0206</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract variance component estimates: correlations</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>mod.UN.nlme<span class="sc">$</span>modelStruct<span class="sc">$</span>corStruct</span></code></pre></div>
<pre><code>## Correlation structure of class corSymm representing
##  Correlation: 
##   1     2     3     4    
## 2 0.708                  
## 3 0.644 0.634            
## 4 0.748 0.744 0.934      
## 5 0.534 0.549 0.718 0.776</code></pre>
<p>As can be seen, each week <em>gets its own</em> variance and also
each pair of weeks <em>gets</em> individual correlations.</p>
</div>
</div>
</div>
</div>
<div id="model-selection" class="section level1">
<h1>Model selection</h1>
<div id="variance-structure" class="section level2 tabset tabset-fade">
<h2 class="tabset tabset-fade">variance structure</h2>
<div id="glmmtmb-5" class="section level3">
<h3>glmmTMB</h3>
<p>In order to select the best model here, we can simply compare their
AIC values, since all models are identical regarding their fixed effects
part. The smaller the value of AIC, the better is the fit:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>AICcmodavg<span class="sc">::</span><span class="fu">aictab</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">cand.set =</span> <span class="fu">list</span>(mod.iid, mod.hCS, mod.AR1, mod.Toep, mod.UN), </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">modnames =</span> <span class="fu">c</span>(<span class="st">&quot;iid&quot;</span>, <span class="st">&quot;hCS&quot;</span>, <span class="st">&quot;AR1&quot;</span>, <span class="st">&quot;Toeplitz&quot;</span>, <span class="st">&quot;UN&quot;</span>),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">second.ord =</span> <span class="cn">FALSE</span>) <span class="co"># get AIC instead of AICc</span></span></code></pre></div>
<pre><code>## 
## Model selection based on AIC:
## 
##           K   AIC Delta_AIC AICWt Cum.Wt    LL
## AR1      42 38.04      0.00  0.96   0.96 22.98
## hCS      46 45.25      7.20  0.03   0.98 23.38
## UN       55 47.10      9.05  0.01   0.99 31.45
## Toeplitz 49 47.88      9.84  0.01   1.00 25.06
## iid      41 78.26     40.22  0.00   1.00  1.87</code></pre>
<p>According to the AIC value, the <code>mod.AR1</code> model is the
best, suggesting that the plot values across weeks are indeed
autocorrelated (as opposed to the <code>mod.iid</code> model) and that
from all the potential variance structures, the first order
autoregressive structure was best able to capture this
autocorrelation.</p>
</div>
<div id="nlme-6" class="section level3">
<h3>nlme</h3>
<p>In order to select the best model here, we can simply compare their
AIC values, since all models are identical regarding their fixed effects
part. The smaller the value of AIC, the better is the fit:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>AICcmodavg<span class="sc">::</span><span class="fu">aictab</span>(</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">cand.set =</span> <span class="fu">list</span>(mod.iid.nlme, mod.CS.nlme, mod.AR1.nlme, mod.AR1nugget.nlme, mod.UN.nlme), </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">modnames =</span> <span class="fu">c</span>(<span class="st">&quot;iid&quot;</span>, <span class="st">&quot;CS&quot;</span>, <span class="st">&quot;AR1&quot;</span>, <span class="st">&quot;AR1 + nugget&quot;</span>, <span class="st">&quot;UN&quot;</span>),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">second.ord =</span> <span class="cn">FALSE</span>) <span class="co"># get AIC instead of AICc</span></span></code></pre></div>
<pre><code>## 
## Model selection based on AIC:
## 
##               K   AIC Delta_AIC AICWt Cum.Wt Res.LL
## AR1 + nugget 43 37.48      0.00  0.42   0.42  24.26
## AR1          42 38.04      0.57  0.31   0.73  22.98
## CS           42 38.38      0.90  0.27   1.00  22.81
## UN           55 47.10      9.62  0.00   1.00  31.45
## iid          41 78.26     40.78  0.00   1.00   1.87</code></pre>
<p>According to the AIC value, the <code>mod.AR1</code> model is the
best, suggesting that the plot values across weeks are indeed
autocorrelated (as opposed to the <code>mod.iid</code> model) and that
from all the potential variance structures, the first order
autoregressive structure was best able to capture this
autocorrelation.</p>
</div>
</div>
<div id="time-trend-as-polynomial-regression-model"
class="section level2">
<h2>time trend as (polynomial) regression model</h2>
<p>So far, we have focussed on dealing with potentially correlated error
terms for our repeated measures data. Now that we dealt with this and
found an optimal solution, we are now ready to select a regression model
for time trend. As a reminder, this is the data we are dealing with
(this time not animated):</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> dat, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">y =</span> y, <span class="at">x =</span> weekF,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">group =</span> variety,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> variety)) <span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.75</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span>mean, <span class="at">geom=</span><span class="st">&quot;line&quot;</span>) <span class="sc">+</span> <span class="co"># lines between means</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Leaf area index&quot;</span>,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">6.5</span>),</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">6</span>)) <span class="sc">+</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> var_colors) <span class="sc">+</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;bottom&quot;</span>, </span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="Repeated_RCBD_PiephoEdmondson2018_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>It can now be asked whether the trend over time is simply linear (in
the sense of <code>y = a + bx</code>) or can better be modelled as with
a polynomial regression (<em>i.e.</em> <code>y = a + bx + cx²</code> or
<code>y = a + bx + cx² + dx³</code> and so on). Very roughly put, we are
asking whether a straight line fits the data well enough or if we should
instead use a model that results in some sort of curved line.</p>
<p>In order to answer this question, we use the <em>lack-of-fit</em>
method to determine which degree of a polynomial regression we should go
with. We start with the linear regression model.</p>
<p></br></br></br></p>
<p><span style="color:red"> work in progress </span></p>
<p></br></br></br></p>
</div>
</div>

&nbsp;
<hr />
<p style="text-align: center;">Please feel free to contact me about any of this!</p>
<p style="text-align: center;"><span style="color: #003f75ff;"><em>schmidtpaul1989@outlook.com</em></span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://www.researchgate.net/profile/Paul_Schmidt17" class="fa fa-pencil" style="color: #003f75ff;"></a>
    <a href="https://www.linkedin.com/in/schmidtpaul1989/" class="fa fa-linkedin" style="color: #003f75ff;"></a>
    <a href="https://www.xing.com/profile/Paul_Schmidt393/cv" class="fa fa-xing" style="color: #003f75ff;"></a>
    <a href="https://github.com/SchmidtPaul/" class="fa fa-github" style="color: #003f75ff;"></a>
</p>

<a href="https://hits.seeyoufarm.com"><img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fschmidtpaul.github.io%2FDSFAIR%2F&count_bg=%23003F75&title_bg=%23555555&icon=&icon_color=%23E7E7E7&title=hits&edge_flat=false" class="center"/></a>

&nbsp;


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
